SELECT * FROM customer;


-- Total Revenue generated by male vs. female customers
select gender, SUM(purchase_amount) as revenue
from customer
group by gender


--Customers who used a discount but still spent more than the average purchase amount 
select customer_id, purchase_amount 
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer);


-- Top 5 products with the highest average review rating
SELECT TOP 5
    item_purchased,
    ROUND(AVG(CAST(review_rating AS FLOAT)), 2) AS [Average Product Rating]
FROM customer
GROUP BY item_purchased
ORDER BY AVG(CAST(review_rating AS FLOAT)) DESC;


-- Comparing the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type, 
ROUND(AVG(purchase_amount),2) AS [Average Purchase Amounts]
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Comparing Average Spend and Total Revenue between Subscribers and Non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount),2) AS avg_spend,
       ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,avg_spend DESC;

--5 products with the highest percentage of purchases with discounts applied
SELECT TOP 5
       item_purchased,
       ROUND(
           100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) 
           / COUNT(*),
           2
       ) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC;



-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 
WITH customer_type AS (
    SELECT 
        customer_id,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer
)
SELECT 
    customer_segment,
    COUNT(*) AS [Number of Customers]
FROM customer_type
GROUP BY customer_segment;


--= Top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category 
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3
ORDER BY category, item_rank;

 
-- Customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Total Revenue contribution of each age group 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue desc;
